// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package jwt

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO refresh_tokens (user_id, expiration_time)
VALUES ($1, $2)
    RETURNING id, user_id, expiration_time, is_available, created_at
`

type CreateParams struct {
	UserID         uuid.UUID
	ExpirationTime pgtype.Timestamptz
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, create, arg.UserID, arg.ExpirationTime)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpirationTime,
		&i.IsAvailable,
		&i.CreatedAt,
	)
	return i, err
}

const get = `-- name: Get :one
SELECT id, user_id, expiration_time, is_available, created_at FROM refresh_tokens WHERE id = $1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpirationTime,
		&i.IsAvailable,
		&i.CreatedAt,
	)
	return i, err
}

const use = `-- name: Use :one
UPDATE refresh_tokens
SET is_available = false
WHERE id = $1 AND is_available = true AND expiration_time > now()
    RETURNING id, user_id, expiration_time, is_available, created_at
`

func (q *Queries) Use(ctx context.Context, id uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, use, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpirationTime,
		&i.IsAvailable,
		&i.CreatedAt,
	)
	return i, err
}
