// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package form

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO forms (title, description, author_id)
VALUES ($1, $2, $3)
    RETURNING id, title, description, author_id, created_at
`

type CreateParams struct {
	Title       string
	Description pgtype.Text
	AuthorID    pgtype.UUID
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Form, error) {
	row := q.db.QueryRow(ctx, create, arg.Title, arg.Description, arg.AuthorID)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE from forms where id =$1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const list = `-- name: List :many
SELECT
    f.id,
    f.title,
    f.description,
    f.author_id,
    f.created_at,
    EXISTS(
        SELECT 1 FROM bookmarks b
        WHERE b.form_id = f.id AND b.user_id = $1
    ) AS is_bookmark
FROM forms f
`

type ListRow struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	AuthorID    pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	IsBookmark  bool
}

func (q *Queries) List(ctx context.Context, userID uuid.UUID) ([]ListRow, error) {
	rows, err := q.db.Query(ctx, list, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRow
	for rows.Next() {
		var i ListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AuthorID,
			&i.CreatedAt,
			&i.IsBookmark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :one
UPDATE forms
SET title = $1, description = $2
WHERE id = $3
    RETURNING id, title, description, author_id, created_at
`

type UpdateParams struct {
	Title       string
	Description pgtype.Text
	ID          uuid.UUID
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (Form, error) {
	row := q.db.QueryRow(ctx, update, arg.Title, arg.Description, arg.ID)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}
