// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	form "awesomeProject/internal/form"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, name, description, author_id
func (_m *Store) Create(ctx context.Context, name string, description string, author_id uuid.UUID) (form.Form, error) {
	ret := _m.Called(ctx, name, description, author_id)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 form.Form
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID) (form.Form, error)); ok {
		return rf(ctx, name, description, author_id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID) form.Form); ok {
		r0 = rf(ctx, name, description, author_id)
	} else {
		r0 = ret.Get(0).(form.Form)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, uuid.UUID) error); ok {
		r1 = rf(ctx, name, description, author_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Store) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, userID
func (_m *Store) List(ctx context.Context, userID uuid.UUID) ([]form.ListRow, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []form.ListRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]form.ListRow, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []form.ListRow); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]form.ListRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, title, description
func (_m *Store) Update(ctx context.Context, id uuid.UUID, title string, description string) (form.Form, error) {
	ret := _m.Called(ctx, id, title, description)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 form.Form
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (form.Form, error)); ok {
		return rf(ctx, id, title, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) form.Form); ok {
		r0 = rf(ctx, id, title, description)
	} else {
		r0 = ret.Get(0).(form.Form)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, id, title, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
