// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	bookmark "awesomeProject/internal/bookmark"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Query is an autogenerated mock type for the Query type
type Query struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, arg
func (_m *Query) Create(ctx context.Context, arg bookmark.CreateParams) (bookmark.Bookmark, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 bookmark.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bookmark.CreateParams) (bookmark.Bookmark, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bookmark.CreateParams) bookmark.Bookmark); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(bookmark.Bookmark)
	}

	if rf, ok := ret.Get(1).(func(context.Context, bookmark.CreateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, arg
func (_m *Query) Delete(ctx context.Context, arg bookmark.DeleteParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bookmark.DeleteParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exist provides a mock function with given fields: ctx, arg
func (_m *Query) Exist(ctx context.Context, arg bookmark.ExistParams) (bool, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Exist")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bookmark.ExistParams) (bool, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bookmark.ExistParams) bool); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, bookmark.ExistParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFormsByUserID provides a mock function with given fields: ctx, userID
func (_m *Query) GetFormsByUserID(ctx context.Context, userID uuid.UUID) ([]bookmark.GetFormsByUserIDRow, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFormsByUserID")
	}

	var r0 []bookmark.GetFormsByUserIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]bookmark.GetFormsByUserIDRow, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []bookmark.GetFormsByUserIDRow); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bookmark.GetFormsByUserIDRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByFormID provides a mock function with given fields: ctx, formID
func (_m *Query) CountByFormID(ctx context.Context, formID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, formID)

	if len(ret) == 0 {
		panic("no return value specified for CountByFormID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, formID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, formID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, formID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByUserID provides a mock function with given fields: ctx, userID
func (_m *Query) CountByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountByUserID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewQuery creates a new instance of Query. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *Query {
	mock := &Query{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
