// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package user

import (
	"context"

	"github.com/google/uuid"
)

const create = `-- name: Create :one
INSERT INTO users (email)
VALUES ($1)
    RETURNING id, email, created_at
`

func (q *Queries) Create(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, create, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const exists = `-- name: Exists :one
SELECT id FROM users WHERE id = $1
`

func (q *Queries) Exists(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, exists, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const existsUser = `-- name: ExistsUser :one
SELECT EXISTS(
    select 1
    FROM users
    WHERE email = $1
)
`

func (q *Queries) ExistsUser(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, existsUser, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getByEmail = `-- name: GetByEmail :one
SELECT id, email, created_at FROM users WHERE email = $1
`

func (q *Queries) GetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getByEmail, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}
