// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package bookmark

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Bookmark struct {
	FormID    uuid.UUID
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type Form struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
	AuthorID    pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type RefreshToken struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	ExpirationTime pgtype.Timestamptz
	IsAvailable    bool
	CreatedAt      pgtype.Timestamptz
}

type User struct {
	ID        uuid.UUID
	Email     string
	CreatedAt pgtype.Timestamptz
}
