// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package bookmark

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countByFormID = `-- name: CountByFormID :one
SELECT COUNT(*) FROM bookmarks WHERE form_id = $1
`

func (q *Queries) CountByFormID(ctx context.Context, formID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countByFormID, formID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countByUserID = `-- name: CountByUserID :one
SELECT COUNT(*) FROM bookmarks WHERE user_id = $1
`

func (q *Queries) CountByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const create = `-- name: Create :one
INSERT INTO bookmarks (form_id, user_id)
VALUES ($1, $2)
    RETURNING form_id, user_id, created_at
`

type CreateParams struct {
	FormID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Bookmark, error) {
	row := q.db.QueryRow(ctx, create, arg.FormID, arg.UserID)
	var i Bookmark
	err := row.Scan(&i.FormID, &i.UserID, &i.CreatedAt)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM bookmarks
WHERE form_id = $1 AND user_id = $2
`

type DeleteParams struct {
	FormID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) Delete(ctx context.Context, arg DeleteParams) error {
	_, err := q.db.Exec(ctx, delete, arg.FormID, arg.UserID)
	return err
}

const exist = `-- name: Exist :one
SELECT EXISTS (SELECT 1 FROM bookmarks WHERE form_id = $1 AND user_id = $2) AS exists
`

type ExistParams struct {
	FormID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) Exist(ctx context.Context, arg ExistParams) (bool, error) {
	row := q.db.QueryRow(ctx, exist, arg.FormID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFormsByUserID = `-- name: GetFormsByUserID :many
SELECT
    b.form_id,
    f.title,
    f.description,
    f.author_id,
    f.created_at
FROM bookmarks b
         JOIN forms f ON b.form_id = f.id
WHERE b.user_id = $1
`

type GetFormsByUserIDRow struct {
	FormID      uuid.UUID
	Title       string
	Description pgtype.Text
	AuthorID    pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetFormsByUserID(ctx context.Context, userID uuid.UUID) ([]GetFormsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getFormsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFormsByUserIDRow
	for rows.Next() {
		var i GetFormsByUserIDRow
		if err := rows.Scan(
			&i.FormID,
			&i.Title,
			&i.Description,
			&i.AuthorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
